
CEBPBCEBPB <- TFregulomeR::intersectPeakMatrix(peak_id_x = "MM1_HSA_K562_CEBPB", motif_only_for_id_y = T,motif_only_for_id_x = T, peak_id_y = "MM1_HSA_K562_CEBPB",motif_type = "TRANSFAC") #intersection of CEBPB-CEBPB
CEBPBCEBPBMatrix <- CEBPBCEBPB["MM1_HSA_K562_CEBPB","MM1_HSA_K562_CEBPB"][[1]]@MethMotif_x@MMmotif@motif_matrix



CEBPBCEBPD <- TFregulomeR::intersectPeakMatrix(peak_id_x = "MM1_HSA_K562_CEBPB", motif_only_for_id_y = T,motif_only_for_id_x = T, peak_id_y = "MM1_HSA_K562_CEBPD",motif_type = "TRANSFAC") #intersection of CEBPB-CEBPD
CEBPBCEBPDMatrix <- CEBPBCEBPD["MM1_HSA_K562_CEBPB","MM1_HSA_K562_CEBPD"][[1]]@MethMotif_x@MMmotif@motif_matrix


CEBPBATF4 <- TFregulomeR::intersectPeakMatrix(peak_id_x = "MM1_HSA_K562_CEBPB", motif_only_for_id_y = T,motif_only_for_id_x = T, peak_id_y = "MM1_HSA_K562_ATF4",motif_type = "TRANSFAC") #intersection of CEBPB-ATF4
CEBPBATF4Matrix <- CEBPBATF4["MM1_HSA_K562_CEBPB","MM1_HSA_K562_ATF4"][[1]]@MethMotif_x@MMmotif@motif_matrix


CEBPBCEBPB4inter <- TFregulomeR::intersectPeakMatrixResult(
  intersectPeakMatrix = CEBPBCEBPB,
  return_intersection_matrix = TRUE,
  save_MethMotif_logo = TRUE
)


CEBPBCEBPD4inter <- TFregulomeR::intersectPeakMatrixResult(
  intersectPeakMatrix = CEBPBCEBPD,
  return_intersection_matrix = TRUE,
  save_MethMotif_logo = TRUE
)

CEBPD_record <- TFregulomeR::dataBrowser(tf = "CEBPD")
CEBPD_record_ID_noK562 <- CEBPD_record$ID[!(CEBPD_record$ID %in% "MM1_HSA_K562_CEBPD")]
exclusivePeak_output <- TFregulomeR::exclusivePeaks(target_peak_id = "MM1_HSA_K562_CEBPD", 
                                       motif_only_for_target_peak = TRUE, 
                                       excluded_peak_id = CEBPD_record_ID_noK562, 
                                       motif_only_for_excluded_peak = TRUE, 
                                       methylation_profile_in_narrow_region = FALSE,motif_type = "TRANSFAC")
CEBPBDexc <- exclusivePeakCEBPD[[1]]@MethMotif@MMmotif@motif_matrix


ATF4_record <- TFregulomeR::dataBrowser(tf = "ATF4")
ATF4_record_ID_noK562 <- ATF4_record$ID[!(ATF4_record$ID %in% "MM1_HSA_K562_ATF4")]
exclusivePeakATF4 <- TFregulomeR::exclusivePeaks(target_peak_id = "MM1_HSA_K562_ATF4", 
                                                    motif_only_for_target_peak = TRUE, 
                                                    excluded_peak_id = ATF4_record_ID_noK562, 
                                                    motif_only_for_excluded_peak = TRUE, 
                                                    methylation_profile_in_narrow_region = FALSE,motif_type = "TRANSFAC")
ATF4exc <- exclusivePeakATF4[[1]]@MethMotif@MMmotif@motif_matrix



TFregulomeR::exportMMPFM(fun_output = exclusivePeak_output, 
            fun = "exclusivePeaks", 
            save_motif_PFM = TRUE, 
            save_betaScore_matrix = TRUE)


TFregulomeR::exportMMPFM(fun_output = CEBPBCEBPB, 
            fun = "intersectPeakMatrix", 
            save_motif_PFM = TRUE, 
            save_betaScore_matrix = FALSE)

TFregulomeR::exportMMPFM(fun_output = CEBPBCEBPD, 
            fun = "intersectPeakMatrix", 
            save_motif_PFM = TRUE, 
            save_betaScore_matrix = FALSE)

CEBPBCEBPBMatrixTFBS <- TFBSTools::PFMatrix(
  profileMatrix = t(CEBPBCEBPBMatrix),
  ID = toString("CEBPBCEBPBMatrix"),
  strand = "*",
  name = paste0("CEBPBCEBPBMatrix object")
)

CEBPBCEBPDMatrixTFBS <- TFBSTools::PFMatrix(
  profileMatrix = t(CEBPBCEBPDMatrix),
  ID = toString("CEBPBCEBPDMatrix"),
  strand = "*",
  name = paste0("CEBPBCEBPDMatrix object")
)

CEBPBDexcTFBS <- TFBSTools::PFMatrix(
  profileMatrix = t(CEBPBDexc),
  ID = toString("CEBPBDexc"),
  strand = "*",
  name = paste0("CEBPBDexc object")
)
CEBPBATF4MatrixTFBS <- TFBSTools::PFMatrix(
  profileMatrix = t(CEBPBATF4Matrix),
  ID = toString("CEBPBATF4Matrix"),
  strand = "*",
  name = paste0("CEBPBATF4Matrix object")
)

ATF4excTFBS <- TFBSTools::PFMatrix(
  profileMatrix = t(ATF4exc),
  ID = toString("ATF4exc"),
  strand = "*",
  name = paste0("ATF4exc object")
)
CEBPBCEBPBMatrix

CEBPBCEBPDMatrix
CEBPBDexc

CEBPBATF4Matrix
ATF4exc
##################################
CEBPBCEBPBMatrixTFBSPWM <- TFBSTools::toPWM(CEBPBCEBPBMatrixTFBS)

CEBPBCEBPDMatrixTFBSPWM <- TFBSTools::toPWM(CEBPBCEBPDMatrixTFBS)
CEBPBDexcTFBSPWM <- TFBSTools::toPWM(CEBPBDexcTFBS)

CEBPBATF4MatrixTFBSPWM <- TFBSTools::toPWM(CEBPBATF4MatrixTFBS)
ATF4excTFBSPWM <- TFBSTools::toPWM(ATF4excTFBS)
#################################
ATF4_B_chr1 <- Biostrings::DNAString("GATCACAAGGTCAGGAGTTTGAGACCAGCCTGGTCAATATGGTGAAACCCCGTCTCTACTAAAAATATGAAAAAATTAGCTGGGCGTGGTAGCACATGCCTGTAATCACAGCTACTCAGGAGGCTGAGGCAGGAGAATCGCTTGAACCTGGGAGGCCGAGGTTGCAGTGAGCTGAGATTGCGCCACTTTACTCCAGCCTGGGTGACAGAGTGAGACTCCGTCTCAAAAAATAAAAAAACAAAAAACAAAAATTGCGGGAGTTAGCCACCATTCTTGGCCTTTTGAGGGACTCTTGATGTGGATTTTTGCTAATTTATGATTTAGTCTCTTGGCTTCTGCTAACTTCAGCTTTGTGTTTTGTAGCCTTCGTGTTTGGATCAGCTTGCCTTGCACCTTTTTTCTTAATCTAAGTGCTTTGTTTACTGTCATTACTTTAATAAATGTTTTATTTTGGTTATTAGCAGTTCTATTTACAATTATACTTCAGTTCTTCCTAGAAAAGTACTATGTAAATCAGATACATTTATGAAAGCTACTCATTAATTATTGTGAGAATAGTGTCCGAATGTTAGCTTAATGGTCATCGTGATTATTTATATTCCTGCACTTTACTTTTTGATTCTTGCAGTATAAACTCCTGTCTTGTTCTCTGGGGAGGAAGCACACTGTGAATTTTTTCCAAGATTGTCTAAAATATTCAGGCTTTTTATTTGCTCTAACCAGTAGAATCTAAAGATTACAGAAACTTTGGAATTTTTCTCCTCATAATTTGACAATCTTTTGAGAGGTTTGTCAGTTGAACACTGTCCCTTTGTTAAAAGTTAATTTTACTTAATAAATAATTTTTCATTAGATTGGAGTAAAATATAATGTGAGTATGTATGTGCATAAATAATTTTTTTTCGGTGAAGTGCGGGTAGCTCATGCCTGTAATCCCAGCACTTTCTGCTTTTTTTTTTTTTGAGACGGAGTCTCGCTCTGTCGCCCAGGCTAGAGTGCAGTGATGCAATCTCAGCTTACTGTAAGCTCCGCCTCCCAGGTTCACGCCATTCTCCTGCCTCAGCCTCCTGAGTAGCTGGGACTACAGGTGCCCACCACCATTCCTGGCTAACTTTTTGTATTTTTAGTAGAGATGGGGTTTCACTGTGTTAGCCAGGATGGCTTCGATCTCCTGACCTTGTGGTCTGCCTACCTCAGCCTCCCAAAGTGGTAGGATTACAGGTGTGAGCCACCGCTCCCGGCCGAATCCCAGCACTTTTCCCATTCTCAGTGGGTAATAAAAGGTAGTTGGGCATGGTGGTATGTACCTATAGTCCAGCTACTTGGAAGGCTTAGGCGGGCAGATCACTTGAACCTGGGAGGTTGAGGCTGCAGTGAGCCAAGATTGTGCCATTGGACTCCAGCCTGGGTGACAGTGACGCTGTCTCAGAAAAACAAAACAAAACTGCACATGCACACACACACAGACACATATAATTTTTTTCCTTACTGGAGTAATGAAGCCTGCAATAGTTCTGAAGAATGTCTGCATTCAGAGCTTTACTGGAAACAGATGCCTTTTCCCAGGAGTTGTAATTATCAAGTTTTCTATGTTCAGGAATCTAGGCACTCACCCTGGATTCAGTAAACAGATAGGGGTATAGTTTTATTGGTTGAATTAAGCTTATTCTTGGTCTTAACATTTTCTTAAAGCCTTTCTACTTAGAACCAATAAATAGTTTCTAATATAAAAAAGTAATCTGGCTGGGTGCAGTGGCTCATACCTGTAATCCCAGCACTTTGGGAGACCGAGACTAGAGGACTGCTTGAGTCCAGGAATTGGAGACCAGCCTAGGCAACATGTTGAGACCTCATCTCTATGGAAAACAAAAACATCAGCTGGGTGTGGTGGTGCCTGCCTGTAGTCCCAGCTGCTTAGGAGGCTGAGATAGGAGGATTGCTTGAGCCTGGGAGGTTGAGGCTGCAGTGAGCCATGATTGCACCACTGCACTCCAGCCTGGGCAACAGAGCA")
ATF4_B_chr3 <- Biostrings::DNAString("AGAATAGCAACACCTATTTACTTGGAGGGAGGAGACTGCAGGGACAGTTTCAGAGCTGGTGACTGTACCAGACAGGGTGGATGAGCACACACAGAGGGAATCCTCCTACCCATCACAGGGCCTGGCTGGCTCCGGTACATCTACCTCCAGTACTTACACACAGGTCCCAGCCCACCCCGCACCATGCACCTCATTTTTTTTTTTTTTTGAGACAGAGTCTTGCTCTGTCACCCAGGCTGGAGTGCAGTAGCCGATATCTTGGCTTACTGCAACCTCTGCTTCCTGGGTTCAAGCAATTTTCGTGTCTCAGCCTCCCTAGTAGCTGGGATTACAGGCACCTGCCACCACGCCCATCTAATTTTTTTTTATTTTTAGTGGAGCTGGTTTTGCCATGTTGGCCAGGCTGGTCTTGAACTCCTGACCTCAGGTGATCCACCCATCTGGCCTCCTACAGTGCTGGGATTACGGGCATGAGCCACCACGCCCGGCTGTACCTCACTTTATAAACAGCTCCTGCTCCTCCTCACTTTATAAACAGCTCCTGCTCCTCCAGGCTTTGCTTTCATGTTTGGAGCTGCAGCCCTCAGACCCTTTATTTCTCTCCACCACTAAAATTCGGATCTTCTTAGGGCCGGAGGCTCACCAAATCTAAAGAGCATACATCAGCCATGAATAATCAGTCGTAGCTGAATTTTTATTGAGCACCACAGAATGCCAGGGACCACGCTAAGCATTTCTCATGTATTATCTCACTGAATTTTTAGGCCTGCTCTATGAGGTTGGGCTATGAACAGTCCCATTTTACATAAGGTAAGACTGAAACTTAGATAAAGTCATTTGCCCATAATCACACAGTTAAGCAGAGGAAAAGCTGGGAGATCTGAACCCAGGCTTAATGACTCCCGGCTGTGAGCTCTGGATCATTCTTTCATCATTGTAGGATTTTATTTTATTTTATTTTAGAGACAGGGTGTTGCTCTGTCACCCAGACTGGAGTGCAGTGATGCAATCATGGCTCACTGGCTGGGCATGGTGGCTGTCGCCTATCATCCCAACATTCTGGGAGGCTGAAGTAGAGGATTGCTTGAGCTCTGGAGTTTGCGATAAGCCTGGGCAACATGGCAAAACCCCATTACTACAATAAAAAGAAAAAAAATTAAAATTGGCTGGGTAGGTGCAGCAAACCACCATGGCACATGTATACCTATGTAACAAGCCTGCACATTCTGCACATGCATCTTGGTTGTTGTTGTTTTTTGTTGTTTTTTTTTTAAGAAGAAGAAATAAAGAAAAAAAAAGAAAGAAAAGAAAAACTGTAAACACTAAAAATGCTTAGTAGTGGTATAGACCCAGCTACTCAGGAGGCTGAGGTGGAGGATTTCTTAAGCTTGGGAGTTCAAGGCTGCAGTGAGCAATGTTCAAGCCCCTGCACTCCAGCCTGGGTGATAGAGACTCTATCTCAAAAAAAAAAAAAAAAAAAAAAAGAAAAAGAAAAAAAAGAAAAGAAAACAAATACTAGTAGTTTATTTTGGGAAAAATAATTAGGAGAACGCTGTCAGTGTCTCTGGTGGGGCAGTGTGGTGTGGTGGTTAATGACACACACTCTAGAGTCAGGCTGCTTGAATTTAAATCTGAGCACTGCTACTTTCTACCTGTGTGACCCTGGGTCATCTATGGAGTGTCTCTGTGCCTTTGCTTTTTTACCTATGGAATAGTACCATCTATCTCATATGATGGACCTGAGGATAAACATGTGAAAAGTGCTCAGGAAACTGAGGCTCAGAGAGGGATAGTGATTCGTCCAAGGTCACACAGCATAGTGACTGGTAGAGCTAGAATTCAAACCTAGGAGTTTCTGATTCCAAAGCCTGTGATTTTCTAAGGCTATTTATGAGTCTAGCACTTTCCCTCTCCAATGGTTCCTCCAACCTCAACATTCTGAGACGAATTATTAAGGAAAAATATTCTCTCTGTGGCATTTCTTCTCTTTTTTGCCTTGAAGTAAAAGCTG")
ATF4_B_chr6 <- Biostrings::DNAString("TCCTCTCTCTGTCTCTGTGTCTCTCTCTTCCTCCTCTTTCTGCCTCCGCCCCTCCCTCTTTCTGTCGTGCGAAGGTCACAACATGGCCTCTGCAGAGGCTTCTCTCATAGGATCTGCCAGTGGTACATGGAAAATCTGGGGCCCAGAAGAGCAGTTTCATTGTGGACCCCCTTGTCAATAAGGGGATATGCTTCCCAGGGACACCTGAAACCATGGAGAGTCCTAAATCCAGTCGCTGTCAATCAGGACACGTGTCTGTTCGTTTTCCACCCATACATTTAATGCCTTCTCCTTCTTAACTGAGCACTATCAGGCCCTGTGGCCATAACTTTTGCAGTTTGAGATGTGATAGTAAAACGAGCGCAAATTTCCTTTTCCCTCATCACATTTTCATGAATAGACTTATTTTTACTGTAGATCTTAGCAAGTTCAGCTTACAATTGTTTTTTCTTTCTGTTTTGTTTTGAGACAGGGTCTGGCTCTGTCGCCCAGGCTGGAGTGTGATGGATCAGTTAAGGCTCCTTGCAGCCTTGACCTGTGGGGCTCAATCATCCTCCAGCCTCACCCCCCCGTACTTGGGATTACAGGCATACCACCATGCCTGGCTACATTTTGTATTTCTTGTAGAGACAGGGTTTTGCTGTGTTGCCCAGACTGGTCTCAAACTCCTGGGCTCGAGTGATCTGCCCACCTCAGCCTCCAAAACTGCTGGGATTCCAGGCGTGAGACACCGCACCTGGCAGCTTTTATTTTCTTAGGAACGTTCACCGTTTCACGTAAAGAAAGCCCTCGATGGCTCCTCTCTGGCAATCTGAATTGCCGGCATCACCGCTCCTGCACCTTGGTGCCATTTTCAAGGAAAATACGGGTTCTTTGAACACACGCACGGCCACCTGGAGAGTCGGCCTCATAAGGGACAGGGTTCCTCAGTGGCTGAGGGACAGGCAGCACCTCCATCGTGGATCCCCTGGGCAAAGCGATGAATCACGTCCCCATGCAAGATTGCATCACACTACTCAGAGCTGTGCACCTTTTAAAACCCAGGAATTATGTATTTCTAGAATTTTCCACTTAATAGATTCGGACCACGGTTGAGTGCGGGTCGCTGAAACAGCGGAAAGTGAAAGCAGGGATAAGGGGGACTGCTGCAGATGCACTTCCTCTGGGTGTCAAGCAGCACACCTCTCCCCCTGCCCCGCCAGGGTGCGGAGGCTGGGCGGTGGCCCCCGTACCAAGGGTGGAGGGAGCGGCCAGGCCACCCTGCCTGTCCCTGTGGGGTGGCCTTCCACTGTTGAGGGTTTAACTGGACATAGTCCTGCACACAAAGACAGGGCAGGCGGTGCTTACTGAACCGTGATTTTTAACAGCGGCATCTTAGCCCGGGTGGGAGAGCCCCGGCGGGGCTCGAGGCTGCAGGTGGGGTTGCACACTCCCAGAGGCTGCCCCACCCCCAGCAATGGGGATGTCTGGGCTGCCAGTTCAGCAGTCGCTGCTTATAAAAAGGAAACTTTAGTGTATGGTATTTTCCTGAATAGTGAGGAAAAAACCCCTGATATCTTACAGTAGAAAATCTCTTCCTCACCTTAAAGAAATCCCTGGGGGTTGGGTGTGGGAGAGGGACATTCCCCTGCCCGATGCTTCCGTCAGCCTAGCCTGACAGATGCTTTGGTTATGTAGTTTCCAGTCATCGGCTGTGGCATTCTCTGCAACACCTCATTGTCCAGATGGTTTCCAGGCACACCTCTTAGCACCTCGCTCACTACCATGCGCTCAACAAGCCAGGCTTCACCTCTGCCCACCTGCCTCCACTTCCTCCTCTTCAGTGAGCTGAGCCGTCCCTGTCCCACCTGGGGATGTTTTTCCACCATCAGGAGCCCCGTCCTCGGTCCCATGCAGCAAGGCCCAGGCAGCGGGCTGGGTGGTAGAGAATCGCCCTGCTCTGTAAAATCTATACCCGAAGCCTGGTTGGAGACACTTGGTTGCAGCCTTGGCCTAAGACTTGATCGTGGAA")
CEBPD_B_chr1 <- Biostrings::DNAString("TATCATCATCCCTTCTTCCTCAGGTTTGGCAGGGCAATGATCATCTGTGGGGCCAGGTACCCATACACTATCATTAACATATACTTCAATAGGATTATCCATCCATGTGACTGGTGTTTCCATCTCCGCGGTGGCGCTTTTCTTTGCATCTCCGATGGGTTCATCGTAGATCTTCAAATGTCTAGTGGGTATCCAAACAGGAAGCTGATTTTCTCCTGGTGAAACACAAGCAAAACCTCTCCCCCACGTCACCACCTTCCCTATTTCCCATGTCTTATTTTTATTATCTTTCCACCAAATCAGTTTTCCTTCATGTGGGCTGTTCTTTTTACCAGTAAAATGTTGTTCTGCAGAAGTAGTAGTCTGATTTCTATAAATGTTTAAAAAATTTAAAGTATAGAGTGCTAGATTAAGTTGCATCTGAGGAGTGGTACATTCCTTACTGTCTCCCCCTTCTTTTTGCTTAACTGAGTTTTGAGTGTTCTATTAGTTCTTTCAACTATGGCCTGTCTGTGGGAATTATAGGGAATTCCTGTTGTATGTGAAACTTTCCACTGATGTAAGAATTTTTGGAAAGCTTTACTACAGTATCCTGGTCCATTGTCAGTTTTGATCTTTTTCTGGAACTCCCATTACAGCAAAACAAGATAATAAATGTTTTTTAACATGGGAAGTACTGTCTCGATTATCTGGCCCTAAACAATGTAAAATCACAGTACTTTGATACACTTCTGAGGCTGTGCCTACGCTGACAAGCCCTGTAACAGCCTTTAGTTTAGGCCAATTTTTGGCCACTGATTTAAAGCAATGATAGAGACATCTGCTCCAGTGTCTACTAACCCTTCAAACTGTTTTCCTTGAATAATGGCCTTACACGCAGGTCTGTTCTCTGAGACCCGACTTGCCCAATATGCAGCCTTTCCTGTTGGATCAGTGCTTCCAAACCCTCCTGTTCTTTTTATCTCACTATTTCCAACCTTAATATAAGGCAGGAGTAATAATTGCGCAATCCTGTCTCCTGGACTGGCACTCCAAGGAATTGAAGAGCTAATAACCAATTGAATTTCGCCATTATAGTCTGAATCAACCACATCAGTACGAATTTGAACTCCCTTCAGACTTAGACTTGATCTACCTAAGATTAGTCCTACAGTCCCCTCAGGCAGTGGGCCATATACCCCTGTGGAGATTTTTTGTGGGGGCTCCCCTGGAAGCAGAGAGACTGCCTTTATAGTACATAAATCCACAGCTGCACTGCCGCTTGTGGCGGGGGACAATTGTTGTACTGTGGTAACTGGCTCATTCCCTGAGGCACTTGGGACAGTGGGGGTTGTTGTCCCTGAAAACCCTGAGGAACAAAGGGCTGAATTGGGAATGCCCCAGTTTGTTGCGGGGCCTGAGGCTGGCCCCTTTGCTCATTTTCCCGACAATGGTTGCCCATTTCTATCAAATTTAGAATGACATTGACTAGCCCAGTGTTTTCCTTGTTTACATCTTGGACATAAGTCAGGTGGCTCTTTTTTATTTGAGACTGGGCAATTCTTTTTTAGATGACCAATTTGATCACAATTATAACATTTCCCTCCAAATGTTCTAACTTGTCCTCCTAAAGCAACTCCTGTTATTGTGGAATAAAGTTTAGAAAATATCCAAAGCTTATCAGCCTGTAAATTCTGGGTAGTTCAGTTGTCTACCATGCTGTTAATTAAATGAAAACATCCTGTTATTTCAGGGTCCTTCCTTGACAAAGTACTATACAGCTGAAGAACATCTCGAATACAATTTTGGTGGGAAAGGAGCCAATTGATTTCAACAGAATCAGATCTGAGCTTCATAAAGTCTTTGAAGTGACTTCACAGAGACGCAGACATGTGCACTTGAAGATGCTGCCCCTTCCCTGGTACCTAGCAAAGCTCCTGCCTCTTTGTGTGCGTCACTGTGAAACCCCCACCCTTCTGCCTCGTGCTAAACGCACACAGTATCTAGTCAGGGGAAAAGACTGCATTTAGGA")
CEBPD_B_chr4 <- Biostrings::DNAString("GTGGAGGTTGCAGTGAGCGGAGATCGTGTCATTGCACTCAAGGCTGGGTGACAGAGCGAGACTCTCTCAAATAAATACATAAATAAAATAAAATAGAAGAAACTGCTGATACACAGAGGGCATGAGGAGGTACTGTGAGGAGGGTGGGGATGGGTGGCAATTTGGAAAGTCAGCAGAGGGCCCTGTATGACAGGGGAGTTTCTGAGTCGAACTGAGAAGGAAGGGAGGGGCCCTGTGTTGAGAAGAAGCAGAGCTCCCCCAGGAGGGAGATCATGGGTGAAAGCCGGAAGGCTTGGTGTCTGCAGAACTCAGAGAGAGCCACAGTTTGGGGCTGTGACCATGGGGACTTTCCTTCCACTCTTTTCCTTGGCCCTGTGCTCAGCCATAACCAGCCACCGAATTTTCCAGAACCTGGGAGGCTGTTTCCAGCCTCAGCGCCTCCGCTACTGCTGTTCCAGCTGCCCGGGATGCCCTTCCCTTACTGGGGAGGTATTTATTCCCTTACCTCCCATTTATCAAGACTTAGTTTGGGCAGCATCTTGCCCAGAAAGCCTCCCCTGACCTAGGGGTGTATTTGGGGCCAGCTCCACAGAGCAGCGATCAGCCTGGCTGCCCTTGTCTCCCCAGCCTCCGGGGCAGGTGCGTATCAGGTTTCCCTCATCACTGCCATCAGCAGAGGGCCTGGCCCTGGTGAGGGCCCAGGAATGTGTCAGTGCAAGCTGCCTCTGGGGAATGTCCTACAGGGCCCTAATGCAGACACTTGGCCCCTCCCCAAGGCCTCACCTGCCCCATGCGCACACCCAGCATTGAGCCTGGAGCGGGTGCCCTCCGCAAGCACTGCTTGCAGAAGGGGCCTTGCCTTTAAAATCACACAAGTTCATAACAAGTGATCTTGTACTTCCGCAAGTTATAATGCATCGTCTTTTATTTTCCAGGCTTCCTGGGATCAGATATGACATTGCACTAATGAGAAATGGGGGTTTCCAGTTGCTCAGGCTCAGATTGCGCAATGGCAGGAAGCATATTAGGTGCTAAAAACTCCCCCTCCCTAGCCGAGCTGGGCGGGTGAGAAGCCGAGTGCGAAACGGGACTTGGCGTGTCATGGGCGCTAAGGAAACGGAGTAAGGCCGACTCACAGGCAGGAACATCGGGACACACACAAAGAGGCAACACCCACTGCGGACGGGGAAACAGACTTTGGTGTTTCATCCACCTCTCAGCGCGCTTATCAGCATCCTGTGACGGCCGGTGCTGCACCCTAACACACACCTAATGACAGACACCAACGCCTTCGCTTGGGGAGCCCGGCCAGCCTCCTGCTCCGGGATGCCCTGCTGGCTTCAAAGATGAGAAGAGCCACATCTCCATCCTATCTCCATCCTATCTCCATCCTTCTCTCCCCAACAGCGTGTGGTTGTCTGTTTCAGGGAGCACATCGCTCCTGGGGCATGTGGGGTTTATGTTTCAGGCTGAGACACCGCCAGCCACAGCACAAGGACGGTGCATCAAGAGCTACGTCGGGTATTAGGCAGGGTACGTGGAAACCCTTGATTCCAGGGCTTTGGCCATCAGAGGAGGATGTTTTCTCCCCAAGACTTGGAAAAATAACAGCAAGGAAAACAGTGGTGGCTATACCTCACATGTATTTACAAAGCGTTCTTTAGAGGGGTCTGTCTTTAAGGTTACCTGTGTGACGAGAAAAAGAAAAAAGAAAAAGAAAAGAAACTAGACAGGGAGCTCTGTGTATGAGGACCACACCAAGAACAGACTGAAACCACACAGATCCGAGCGGTGGAGAATAAGGCTGGAGGCCGCTCCCCTGCGGAGGGACCGTAAAATTAAACTCTATATATGTCATCTCGCGTTTAAGTAGGCTATACTTTTTAATAAAATAAAAACTTCTGTGTTACTTTAAAGATATTGTGTAGGCATCTAGGGGTCGATCTGGAGGAGGAACGCAGCGCATGGAGGGGCGCTGGCGGAAGGTGCCCTGTCTTGTCCCTTGTTGACA")
CEBPD_B_chr17 <- Biostrings::DNAString("GCAGCGGAGCCATGAAGGCCTGCGCAGGACAGGCCAGCTGCGTTGATAGTGTGGGCGGTGCCCTGGAGGGCATCTTGAATCCTTGTCCTCGCTGGTAATTAATGGCCAGGTAGCGTGTTAGGGAGTAGATGTATAGTCACTCTCGAAACTGTTTCTCTGTTGGGTGTTGAGCTCTTCCCACATCAGGAATGAGACTGTTTGCTTCTCTCTTTGTGAGTTCTTCAGGCCCAGGCTCTGGACATGGGCTCACTGTATCAGGAGTGTGGAAGCATCGTGGCTCTTGCATGTGGCCGTGTGCTGCTGTCTGAGTGCCAGCTTTGTCCACACCCTGTCTCTTGTCCTTGGTGGCATAGTGCACACAGTGGCACAACTGGAGACTTGGACTCGAGAAAGGAGAAGTACAAGTTGGATTCAGCCATGTGCGGGGGCAGGCCCTGGCTTGTGTCTACTTGCGCCTCAGTGCTGATCGTCCCTCACTCCTGGGTGCTGACCAGCGTTGTCCTAGTGACCTGGGAGCTCAGGTGTGGGAGGCAGAGGTGCAGTGCAGCCTGGCTTGCCCAGGTCTTGGCTGGGAGGGCCTTCCAGCAGCACTCAGAGCTGTTAGGGAGCAGTTACCTTTTCAGCTGGGTGGGGGTGACTAATAAGTGTACCTGTAGACTTGTGTTTATTTATTTGGTCATTGGAGCCCAACTTTGTACTGGGTGCTTCACTGGATGAGGCAGGATTCTTGTCCCCAGCGAGGAGATGTGGTGTTGTGAGAGAGAAGGAATACATTTGGCCTGGAGCCGGTTAGTGTTCTTGAAGGAGGTGTGGGATTTTGAGGGGTCTGTGTATGAGACAGTGAATCTCCTTATTCCATGGAATAGAAGATGTTTGTGTATGGGAGGTGAGGGGGCATGGGACCATAGAGGGCCTTCTGGGTGGCAGGATGTGATGGGGTGAGAAGAGTGAGACCCACCTGTCTGCATCGACTGTTTGAGGCCTGCCCTCTTTGGTGCCGGATTGCGCAATATGTCTGACTACCTTTCTCCCCACCCACTGCAGTCTAAGGACAGGTGAGTCCAAGGGGACAGGAAACCTGGGTTAACCACCGTTAGAGATCTTGTCACCGACTGTTCCCTTCTCTTGGAGCCACAAACAGGCCACACGGAGTGAGAGCCAAGCATGTTGTGTGGGCTGGTTGTGATGGGGTGGCTGTGTCCAGAGACCTGTGCACGTCTGAGACGCATCAGTGGTGGCAGCTTGACAACACTGGGTATAGTAGGCTGAGATGTTTCTCTGTCCCTTGCCCCTGGCCACCCGCTTGGGGCAGTTGGGCAACCCAGAGTTGAGACAGCTGGGTTCATCCTGGCATGCATCCCAGATTTGCCTGGGGAGGGTGGTGAGGGGAAGGGACAGAAGAACCCTTGAGAGAAGGGATGTGGGTGGCCTCCAGGGAAGTAGTTGGAGAGGCCAGCAGAGCATACGCGGTGCAGCTCAGGGCCATGGCAGGCAGGCGTCACTGAAGAAGGCCCGTGGCCATACCCTGTAGACCCCTGAGGACTGACTGCAGAGGCCACAGTGGCTGAGTTTTGTTTTTCGGTTTTTTTTGTTTTGTTTTTTTTTTTTTGAGATGGAGTCTATCTCTGTTGCCCAGGCTGGGGTGCAGTGGCGCAATCTCGGCTCACTGCAACCTCCGCTTCCTGGGTTGAAGCGATTCTCCTGCCTCGGCGTCCCAAGTAGCTGGGACTACAGGTGCGTGCCACTGTTTTTCCTTTTTTATTAAACTACTTACGTTGAGATAATCGTGTTTCCCCTGTGGTTGTAACAAATAACAGAGATCCCATGTACCCCTTTGCCCAGGTCCTCCGATGGTGACCTTCTGCAACACTGTGGTACGGCACCACGGCTGGGATACTGACTACAATGCAGAAAGCACCCAGTGTCTCCATCGCCTTCTCCCTCCCACATCAACCCAACCCCAGCCACCCAGGAATCCTGCTCCATTTCCATAAATCTGACATTTCAAGAA")


CEBPD_B_chr1_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPDMatrixTFBSPWM, subject = CEBPD_B_chr1, seqname="CEBPDB-chr1", min.score="75%", strand="*")
CEBPD_B_chr17_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPDMatrixTFBSPWM, subject = CEBPD_B_chr17, seqname="CEBPDB-chr17", min.score="75%", strand="*")
CEBPD_B_chr4_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPDMatrixTFBSPWM, subject = CEBPD_B_chr4, seqname="CEBPDB-chr4", min.score="75%", strand="*")
####
CEBPD_B_ALL <- append(append(as.array(CEBPD_B_chr1_scanned@views@ranges@start),as.array(CEBPD_B_chr17_scanned@views@ranges@start)),as.array(CEBPD_B_chr4_scanned@views@ranges@start))

CEBPD_exc_chr1_scanned <- TFBSTools::searchSeq(x=CEBPBDexcTFBSPWM, subject = CEBPD_B_chr1, seqname="CEBPDexc-chr1", min.score="75%", strand="*")
CEBPD_exc_chr17_scanned <- TFBSTools::searchSeq(x=CEBPBDexcTFBSPWM, subject = CEBPD_B_chr17, seqname="CEBPDexc-chr17", min.score="75%", strand="*")
CEBPD_exc_chr4_scanned <- TFBSTools::searchSeq(x=CEBPBDexcTFBSPWM, subject = CEBPD_B_chr4, seqname="CEBPDexc-chr4", min.score="75%", strand="*")
####
CEBPD_exc_ALL <- append(append(as.array(CEBPD_exc_chr1_scanned@views@ranges@start),as.array(CEBPD_exc_chr17_scanned@views@ranges@start)),as.array(CEBPD_exc_chr4_scanned@views@ranges@start))



ATF4_exc_chr1_scanned <- TFBSTools::searchSeq(x=ATF4excTFBSPWM, subject = ATF4_B_chr1, seqname="ATF4exc-chr1", min.score="75%", strand="*")
ATF4_exc_chr3_scanned <- TFBSTools::searchSeq(x=ATF4excTFBSPWM, subject = ATF4_B_chr3, seqname="ATF4exc-chr3", min.score="75%", strand="*")
ATF4_exc_chr6_scanned <- TFBSTools::searchSeq(x=ATF4excTFBSPWM, subject = ATF4_B_chr6, seqname="ATF4exc-chr6", min.score="75%", strand="*")
####
ATF4_exc_ALL <- append(append(as.array(ATF4_exc_chr1_scanned@views@ranges@start),as.array(ATF4_exc_chr3_scanned@views@ranges@start)),as.array(ATF4_exc_chr6_scanned@views@ranges@start))



ATF4_B_chr1_scanned <- TFBSTools::searchSeq(x=CEBPBATF4MatrixTFBSPWM, subject = ATF4_B_chr1, seqname="ATF4B-chr1", min.score="75%", strand="*")
ATF4_B_chr3_scanned <- TFBSTools::searchSeq(x=CEBPBATF4MatrixTFBSPWM, subject = ATF4_B_chr3, seqname="ATF4B-chr3", min.score="75%", strand="*")
ATF4_B_chr6_scanned <- TFBSTools::searchSeq(x=CEBPBATF4MatrixTFBSPWM, subject = ATF4_B_chr6, seqname="ATF4B-chr6", min.score="75%", strand="*")
####
ATF4_B_ALL <- append(append(as.array(ATF4_B_chr3_scanned@views@ranges@start),as.array(ATF4_B_chr1_scanned@views@ranges@start)),as.array(ATF4_B_chr1_scanned@views@ranges@start))


CEBPBallD_chr1_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = CEBPD_B_chr1, seqname="CEBPDBall-chr1", min.score="75%", strand="*")
CEBPBallD_chr17_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = CEBPD_B_chr17, seqname="CEBPDBall-chr17", min.score="75%", strand="*")
CEBPBallD_chr4_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = CEBPD_B_chr4, seqname="CEBPDBall-chr4", min.score="75%", strand="*")
####
CEBPBall_inD_ALL <- append(append(as.array(CEBPBallD_chr1_scanned@views@ranges@start),as.array(CEBPBallD_chr17_scanned@views@ranges@start)),as.array(CEBPBallD_chr4_scanned@views@ranges@start))



CEBPBallATF4_chr1_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = ATF4_B_chr1, seqname="CEBPBallATF4-chr1", min.score="75%", strand="*")
CEBPBallATF4_chr3_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = ATF4_B_chr3, seqname="CEBPBallATF4-chr3", min.score="75%", strand="*")
CEBPBallATF4_chr6_scanned <- TFBSTools::searchSeq(x=CEBPBCEBPBMatrixTFBSPWM, subject = ATF4_B_chr6, seqname="CEBPBallATF4-chr6", min.score="75%", strand="*")
####
CEBPBall_inATF4_ALL <- append(append(as.array(CEBPBallATF4_chr1_scanned@views@ranges@start),as.array(CEBPBallATF4_chr3_scanned@views@ranges@start)),as.array(CEBPBallATF4_chr6_scanned@views@ranges@start))
##################################################################

##Peaks

commonPeak_CEBPBD_output <- TFregulomeR::commonPeaks(target_peak_id = "MM1_HSA_K562_CEBPB",
                                                     motif_only_for_target_peak = TRUE, 
                                                     compared_peak_id = "MM1_HSA_K562_CEBPD", 
                                                     motif_only_for_compared_peak = TRUE, 
                                                     methylation_profile_in_narrow_region = FALSE)

commonPeak_CEBPBD_result <- TFregulomeR::commonPeakResult(commonPeaks = commonPeak_CEBPBD_output,
                                                          return_common_peak_sites = TRUE, 
                                                          save_MethMotif_logo = TRUE, 
                                                          return_methylation_profile = TRUE, 
                                                          return_summary = TRUE)

common_peak_list_CEBPBD <- commonPeak_CEBPBD_result$common_peak_list
